name: Comment on Repo Issue

on:
  workflow_dispatch:

permissions:
  issues: write

jobs:
  comment-on-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Comment if past date
        uses: actions/github-script@v7
        with:
          script: |
            const issues = await github.paginate(
              github.rest.issues.listForRepo,
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open',
                per_page: 100
              }
            );

             const today = new Date();

            for (const issue of issues) {
              const createdAt = new Date(issue.created_at);

              if (today > createdAt) {
                const comment = `This issue was created on ${createdAt.toDateString()}, and today is ${today.toDateString()}. Just leaving a comment because the date has passed.`;

                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  body: comment
                });

                console.log(`Wrote a comment on issue #${issue.number}`);
              } else {
                console.log(`Skipped issue #${issue.number}, date not reached.`);
              }
            }
