name: Comment on Project Issues Based on Timeline

on:
  workflow_dispatch:

permissions:
  issues: write

jobs:
  timeline-commenter:
    runs-on: ubuntu-latest

    steps:
      - name: Comment on issues based on timeline
        uses: actions/github-script@v7
        with:
          script: |
            const issues = await github.paginate(
              github.rest.issues.listForRepo,
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open',
                per_page: 100
              }
            );

            const today = new Date();
            const todayStr = today.toISOString().split('T')[0]; /

            for (const issue of issues) {
              try {
                const body = issue.body || "";

                const startMatch = body.match(/Start Date:\s*(\d{4}-\d{2}-\d{2})/i);
                const endMatch = body.match(/End Date:\s*(\d{4}-\d{2}-\d{2})/i);

                const startDateStr = startMatch?.[2];
                const endDateStr = endMatch?.[2];

                if (!startDateStr && !endDateStr) {
                  console.log(`Skipped Issue #${issue.number} cos no start or end date found.`);
                  continue;
                }

                let comment = null;

                if (startDateStr === todayStr) {
                  comment = `Note that this task starts today (${todayStr})`;
                } else if (endDateStr === todayStr) {
                  comment = `Gentle reminder: This task is scheduled to end today (${todayStr})`;
                }

                if (comment) {
                  await github.rest.issues.createComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: issue.number,
                    body: comment
                  });
                  console.log(`Commented on issue #${issue.number}`);
                } else {
                  console.log(`ℹIssue #${issue.number} has no timeline event today.`);
                }
              } catch (err) {
                console.error(`Error processing issue #${issue.number}:`, err.message);
              }
            }
